### PR TITLE
Remove profile_name collection

### PR DESCRIPTION
**Pull request by DuaelFr**
Use minimal profile during `drupal ibs` command to initialize the setting.
Add a step in the README for people that need another profile.

(In our personal case, the setting will be updated by Kumquat)

### CODE REVIEW

**Review by Artusamak — COMMENTED** [review]
If we are going there, since it's used in only one place, let's remove this setting from composer.json extra and let the users update the string in the install.sh file. It will be more intuitive and less cluttering.

**Comment by DuaelFr** [comment]
We could do that but it'd be far more complicated for less-technical users and for our other tools (like Kumquat Scaffolder).

**Comment by Artusamak** [comment]
Unless i missed something in Kumquat Scaffolder, the only reference to Combawa exists to set the profile name generated in the Composer Extra section.

Meanwhile it's convenient to have it auto generated, the cost to remove this code portion is very low and only implies to manually update the string in the install.sh file.
I wouldn't call it "far more complicated", the consequence is to document this step in Combawa README and optionally also in Kumquat Kickstart.
Truth being told, a less technical user is never going to add this package to its project and if so, i trust its intelligence for being able to follow the README asking to rename the installation profile to run (if it needs to be changed).

I honestly think that we can remove it.

**Comment by Artusamak** [comment]
We agreed to remove the entry from the composer file and will keep asking for the profile name in the interactive command.

Some black magick voodoo is going to happen in kumquat to avoid a double collection. Here a :sheep: for sacrifice.

**Comment by DuaelFr** [comment]
My version: we agreed to remove the entry from the composer file and still stop asking for the profile name in interactive command (so add a line in documentation to let users update it if needed).

Some black magic is going to happen in kumquat to replace the profile name in the install.sh file by the one generated. Thanks for the :sheep: I'll set it free so he can enjoy the grass out there alive ;)

**Comment by DuaelFr** [comment]
Here we go @Artusamak :)

**Review by Artusamak — APPROVED** [review]

**Comment by Artusamak** [comment]
Looks good! Let's try to remember that it will probably break our IC jobs since we will send an unknown argument for the profile name. I don't know if it screams or just ignore the unused argument when such case happen.

**Comment by DuaelFr** [comment]
This command is not used in IC :)
In case it did, it would scream!

**Pull request merged**
